### ISSUE TITLE
Stock prices beyond two decimal places

### ISSUE THREAD

**Issue by jasongaare** [tarkah/tickrs#123] opened 2021-04-29 20:30 UTC
Great tool, I instantly loved it. 

I have OTC penny stocks, which often are represented to 4 decimal places.

`tickrs` rounds all the prices to two places, (it seems) so the data and charts a little less-than-compelling.

<img width="955" alt="Screen Shot 2021-04-29 at 3 28 47 PM" src="https://user-images.githubusercontent.com/15896334/116614474-9a131200-a8ff-11eb-8e90-0af8933186c2.png">

Would it be possible to support more decimal places, perhaps as a config options (even per symbol would be awesome!)

**Comment by tarkah** [comment] 2021-04-29 20:47
Great suggestion! I never even realized this. I could always just hard code it... so anything under ~$2 goes to the 4th decimal place?

Do you have any suggestions on what a good cutoff would be before stock prices start moving in 0.01+ increments?

**Comment by miraclx** [comment] 2021-04-29 21:03
How about we vary it based on the abs max-min delta within the active timeframe? In order to chart out reasonable fluctuations. So it doesn't require hardcoding, works for wholes and decimals alike, and can better spread out charts like the one above.

**Comment by jasongaare** [comment] 2021-04-30 14:11
I like the idea of using the delta. I'm not sure what the threshold is for when the decimals get truncated more.

**Comment by tarkah** [comment] 2021-05-07 17:15
Ok, I've implemented this in #125. Here is an example:

![image](https://user-images.githubusercontent.com/10239377/117485226-f9cf7580-af1c-11eb-9197-2c906d625936.png)

I take the difference between the min and max price within the timeframe, and if it's <= 1.0, then I show 4 decimal places. Seems to work well!

**Comment by tarkah** [comment] 2021-05-07 20:53
@miraclx @jasongaare Can you both test for me for a few days? I think I went too aggressive with the $1.0 delta cutoff, as that'd trigger on a $100 stock with < 1% movement from high to low.

I should have waited to release, but oh well :P

**Comment by tarkah** [comment] 2021-05-07 20:57
Maybe an alternative implementation would look at the period over period price change for the entire time frame, and take the median price change from that. If median is less than $0.01, it's a good candidate for 4 decimals?

**Comment by miraclx** [comment] 2021-05-07 21:08
> I should have waited to release, but oh well :P

😅, I was literally in the process of reviewing and eventually testing the PR when it got merged, I thought, "oh, you're in a hurry".

**Comment by tarkah** [comment] 2021-05-07 21:54
So I tried the method of calculating period over period price movements, then  taking the median, and seeing if it was <= $0.005 (half a cent) and this seems to work really well. However, it massively increases CPU usage due to the calculation...

Any other thoughts?

**Comment by miraclx** [comment] 2021-05-07 22:05
Hmm. Could you open a draft PR for this? Lemme inspect that for a sec.

**Comment by tarkah** [comment] 2021-05-07 22:11
And to clarify, this now JUST impacts the "formatting" of decimal places.

I've fixed the issue where it doesn't graph from top to bottom, which was a separate issue. (I was adding 0.05 padding to high and low price for y-axis bounds, which caused stocks with low prices to be affected).

**Comment by miraclx** [comment] 2021-05-08 00:22
Thought about this for a sec...I still think I still approve of the already merged PR. A stock with < 1% movement in any timeframe should be in four decimal places irrespective of whether or not it's a penny stock or WDYT? This makes sense to me, to graph out reasonable fluctuations like you set out to do in the first place.

Maybe I'm ignorant, but I'm not sure the method of taking median is much of a solution. The gained cost from the required heap allocation, eventual sorting, only to end up, like you said, producing false positives _(which I believe would happen more often than not)_, I don't think is really helpful.

I'll look at it again in the morning, perhaps I'm missing something.

<details>
 <summary>Also, on heap allocation, <code>StockState::high_low</code> could be rewritten without the Vec</summary>

```diff
diff --git a/src/widget/stock.rs b/src/widget/stock.rs
index 60be048..433d384 100644
--- a/src/widget/stock.rs
+++ b/src/widget/stock.rs
@@ -413,29 +413,27 @@ impl StockState {
         (min, max)
     }
 
-    pub fn high_low(&self, data: &[Price]) -> (f64, f64) {
-        let mut data = data.to_vec();
-        data.push(Price {
-            close: self.current_price(),
-            open: self.current_price(),
-            high: self.current_price(),
-            low: self.current_price(),
-            ..Default::default()
-        });
-        data.retain(|p| p.close.gt(&0.0));
-
-        let high = data
+    pub fn high_low(&self, prices: &[Price]) -> (f64, f64) {
+        let data = prices
             .iter()
-            .max_by(|a, b| a.high.partial_cmp(&b.high).unwrap())
-            .map(|p| p.high)
-            .unwrap_or(1.0);
-        let low = data
-            .iter()
-            .min_by(|a, b| a.low.partial_cmp(&b.low).unwrap())
-            .map(|p| p.low)
-            .unwrap_or(0.0);
+            .cloned()
+            .chain(std::iter::once(Price {
+                close: self.current_price(),
+                open: self.current_price(),
+                high: self.current_price(),
+                low: self.current_price(),
+                ..Default::default()
+            }))
+            .filter(|p| p.close.gt(&0.0));
+
+        let (high, low) = data.fold((None::<f64>, None::<f64>), |(pre_h, pre_l), price| {
+            (
+                Some(pre_h.map_or(price.high, |pre_h| pre_h.max(price.high))),
+                Some(pre_l.map_or(price.low, |pre_l| pre_l.min(price.low))),
+            )
+        });
 
-        (high, low)
+        (high.unwrap_or(1.0), low.unwrap_or(0.0))
     }
 
     pub fn x_bounds(&self, start: i64, end: i64, data: &[Price]) -> [f64; 2] {
```

</details>

**Comment by jasongaare** [comment] 2021-05-12 19:30
Not sure the status on this, I still have version 0.14.5... here's a screenshot:

<img width="277" alt="Screen Shot 2021-05-12 at 2 27 02 PM" src="https://user-images.githubusercontent.com/15896334/118033387-5e7c3d00-b32e-11eb-8a55-1b5787c80c40.png">

if you went with the previous solution, is it simply possible to round numbers? Here you can see HYSR and KODK both are getting data with four decimal points, but PBR is always showing x.xx00. Would it be simple to just round of trailing zeros in this case? (not beyond two decimals, obviously)

**Comment by tarkah** [comment] 2021-05-12 22:48
Unfortunately >2 decimal precision prices aren't just something that happens on low prices stocks. SPY, for example, is trading around ~400 and it goes out to like 8 decimal places.

@miraclx  I really don't think it's worth showing more than 2 decimal precision on anything above a certain price, even if its movement is small for the day. At $5, a $0.01 change is only 0.2%. I think I will go with the original implementation, but add a second check that ONLY shows 4 decimal places if the High price is also lower than $5.

**Comment by tidux** [comment] 2022-01-24 13:13
High precision is desirable for crypto pairs since BTC price tends to dwarf anything else.  Check `tickrs -s ETH-BTC` to reproduce.

![Screenshot 2022-01-24 051245](https://user-images.githubusercontent.com/1330562/150789026-0862aba1-07ca-4b02-a499-573820c189ce.png)

**Comment by tarkah** [comment] 2022-01-24 17:30
@tidux I've implemented a better way to dynamically add precision based on the asset price. See #134.

Let me know if you think this works.

![image](https://user-images.githubusercontent.com/10239377/150834049-689ea2a5-98c4-4cc1-8a67-b4a35f16abb6.png)

**Comment by tidux** [comment] 2022-01-25 10:13
That looks good.

**Closed** 2022-08-17 15:46 UTC
Labels: enhancement, good first issue
